---
title: "actually it's gonna be pax ridership for the top 10 Amtrak stations"
author: "Gerrit Blauvelt"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(robotstxt)
paths_allowed("https://en.wikipedia.org/wiki/List_of_busiest_Amtrak_stations")
paths_allowed("https://new.mta.info/agency/new-york-city-transit/subway-bus-ridership-2020")
```

```{r}
amtkstations <- read_html("https://en.wikipedia.org/wiki/List_of_busiest_Amtrak_stations")
amtkstations
mta <- read_html("https://new.mta.info/agency/new-york-city-transit/subway-bus-ridership-2020")
mta

typeof(amtkstations)
class(amtkstations)
typeof(mta)
class(mta)

# amtkRank <- amtkstations %>%
#   html_nodes("tbody th") %>%
#   html_text() %>%
#   str_remove("\\\n") %>%
 
amtkStationName <- amtkstations %>%
  html_nodes("td:nth-child(2)") %>%
  html_text() %>%
  str_remove("\\\n")

amtkCity <- amtkstations %>%
  html_nodes("td:nth-child(3)") %>%
  html_text() %>%
  str_remove("\\\n")

amtkState <- amtkstations %>%
  html_nodes("td:nth-child(4)") %>%
  html_text() %>%
  str_remove("\\\n")

amtkRegion <- amtkstations %>%
  html_nodes("td:nth-child(5)") %>%
  html_text() %>%
  str_remove("\\\n")

amtk2015 <- amtkstations %>%
  html_nodes("td:nth-child(6)") %>%
  html_text() %>%
  str_remove("\\\n") %>%
  {as.numeric(gsub(",","",.))} #since this is special, it needs {} and then a . as a data marker for it to pipe properly

amtk2016 <- amtkstations %>%
  html_nodes("td:nth-child(7)") %>%
  html_text() %>%
  str_remove("\\\n") %>%
  {as.numeric(gsub(",","",.))}

amtk2017 <- amtkstations %>%
  html_nodes("td:nth-child(8)") %>%
  html_text() %>%
  str_remove("\\\n")  %>%
  {as.numeric(gsub(",","",.))}

amtk2018 <- amtkstations %>%
  html_nodes("td:nth-child(9)") %>%
  html_text() %>%
  str_remove("\\\n") %>%
  str_remove("\\[") %>% #someone was so generous as to include citations in this fiscal year, so each value ends with [x], where x is each citation ref number, so we need to remove the [], and then remove that final floating number
  str_remove("\\]") %>%
  {as.numeric(gsub(r"{\s*\[[^\]+\)}","",.))} %>% #trying to gsub out the stuff within the [], but no clue how to parse regex or whatever this even is
  #str_sub(end = -2) %>% #tells R that the string actually starts one character over. I'll be honest, I don't quite understand the logic of -2 meaning get rid of the final character, but that's what the guide said, and it worked --- This worked so well, except for the bit where some of the values have citation numbers that are 10+, meaning it adds 2 chars, not just 1. 
  {as.numeric(gsub(",","",.))}


amtk2019 <- amtkstations %>%
  html_nodes("td:nth-child(10)") %>%
  html_text() %>%
  str_remove("\\\n") %>%
  {as.numeric(gsub(",","",.))}

amtk2020 <- amtkstations %>%
  html_nodes("td:nth-child(11)") %>%
  html_text() %>%
  str_remove("\\\n") %>%
  {as.numeric(gsub(",","",.))}


amtk2015total <- sum(amtk2015) 
amtk2016total <- sum(amtk2016)
amtk2017total <- sum(amtk2017)
amtk2018total <- sum(amtk2018)
amtk2019total <- sum(amtk2019)
amtk2020total <- sum(amtk2020) 

amtk2015total
amtk2016total
amtk2017total
amtk2018total
amtk2019total
amtk2020total




#amtkRank
amtkStationName
amtkCity
amtkState
amtkRegion
amtk2015
amtk2016
amtk2017
amtk2018
amtk2019
amtk2020

AMTRAK <- tibble(
  Station = amtkStationName,
  City = amtkCity,
  State = amtkState,
  Region = amtkRegion,
  "2015" = amtk2015,
  "2016" = amtk2016,
  "2017" = amtk2017,
  "2018" = amtk2018,
  "2019" = amtk2019,
  "2020" = amtk2020
)
AMTRAK



```