---
title: "Gerrit HW 2023-01-09"
author: "Gerrit Blauvelt"
date: "2023-01-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)



ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = class, color=hwy, shape = drv))

ggplot(data = mpg) + geom_point(mapping = aes(x = hwy, y = hwy, color = class, shape = class, stroke = year))

ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class)) +
  facet_wrap(~ class, nrow = 2)

ggplot(data = mpg) +
  geom_point(mapping = aes(x = drv, y = cyl, color = class)) +
  facet_wrap(~ class, nrow = 2)
             
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth(se = FALSE)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth(mapping = aes(group = drv), se = FALSE)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point() + 
  geom_smooth(se = FALSE)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color=drv)) + 
  geom_smooth(se = FALSE)

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color=drv)) + 
  geom_smooth(se = FALSE, mapping = aes(linetype = drv))
```
``` {r} #i got tired of re-knitting the whole document over and over, so here we are
library(tidyverse)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(color = "white", size = 5)+
  geom_point(aes (color = drv), size = 2 )
```



             
``` 